version: "3.7"
services:
    wp-mariadb:
        image: mariadb:10.5.5
        container_name: ${WORDPRESS_DB_HOST}
        restart: always
        ports:
            - "33306:3306"
        environment:
            MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
            MYSQL_USER: ${WORDPRESS_DB_USER}
            MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        volumes:
            - /var/www/html/wp-db-compose/init/init.sql:/docker-entrypoint-initdb.d/init.sql
            - /var/www/html/wp-db-compose/mysqldata/:/var/lib/mysql
            - /var/www/html/wp-db-compose/mysql_config/:/etc/mysql/
        networks:
            - bridge
#command: --default-authentication-plugin=mysql_native_password

    wp-php:
        depends_on:
            - wp-mariadb
        image: wordpress:php8.0-fpm
        container_name: ${CONTAINER_PHP}
        restart: always
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        volumes:
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./wordpress:/var/www/html
        networks:
            - bridge

    wp-web:
        links:
          - wp-php
        image: nginx:latest
        container_name: ${CONTAINER_WEB}
        restart: always
        environment:
            - TZ=Asia/Taipei
#        ports:
#          - "8443:80"
        volumes:
#            - ./logs:/var/log/nginx
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./realip.conf:/etc/nginx/nginx.conf
            - ./wordpress:/var/www/html
            - ./admission-ebook/2024:/var/www/html/admission-ebook/2024
        networks:
            - bridge

networks:
    bridge:
        external: true
        name: ${NETWORKS}