version: "3.3"
services:
    wp-mariadb:
        image: mariadb:latest
        container_name: ${DB_HOST}
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - /home/skyyu/git/wp-db-compose/init/init.sql:/docker-entrypoint-initdb.d/init.sql
            - /home/skyyu/git/wp-db-compose/mysqldata/:/var/lib/mysql
            - /home/skyyu/git/wp-db-compose/mysql_config/:/etc/mysql/
        networks:
            - web
#command: --default-authentication-plugin=mysql_native_password

    wp-php:
        depends_on:
            - wp-mariadb
        image: wordpress:php8.0-fpm
        container_name: wp-php
        restart: always
        environment:
            WORDPRESS_DB_HOST: wp-mariadb:3306
            WORDPRESS_DB_NAME: ${DB_DATABASE}
            WORDPRESS_DB_USER: ${DB_USERNAME}
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - /home/skyyu/git/official-site-WP/wordpress:/var/www/html
        dns:
            - 8.8.8.8
        networks:
            - web

    wp-web:
        links:
          - wp-php
        image: nginx:latest
        container_name: wp-web
        restart: always
        environment:
            - TZ=Asia/Taipei
        ports:
          - "8443:80"
        volumes:
#            - ./logs:/var/log/nginx
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - /home/skyyu/git/official-site-WP/wordpress:/var/www/html
#            - ./wordpress:/var/www/html
        networks:
            - web

networks:
    web:
        external: true
